### ISSUE TITLE
no redirect

### ISSUE THREAD

**Issue by cljag** [gregorionuti/Joomla-Digi-Get-Login#1]
ciao, ottima estensione anzitutto!
credi sia possibile evitare un redirect ad un link fisso, dopo il login? mi piacerebbe creare diversi qrcode con il link precompilato che porta a specifiche pagine protette, es:
https://miosito.com/index.php?option=com_joodb&view=catalog&Itemid=101%username=user&password=pass
https://miosito.com/index.php?option=com_joodb&view=catalog&Itemid=102%username=user&password=pass
https://miosito.com/index.php?option=com_joodb&view=catalog&Itemid=103%username=user&password=pass
https://miosito.com/index.php?option=com_joodb&view=catalog&Itemid=104%username=user&password=pass

**Comment by gregorionuti** [comment]
Ciao. Grazie.
Per come funziona il plugin, quello che chiedi non è possibile; al momento il plugin consente il redirect su una sola voce di menu. Potresti provare a modificare il codice, a creare un'opzione ed aggiungere una funzionalità che prenda l'url inviato al plugin, e di conseguenza faccia il redirect lì, una volta completato il login.
Se vuoi fai pure una pull request con il codice modificato, magari può far comodo anche ad altro utenti.

**Comment by cljag** [comment]
magari essere capace ;) sono un ristoratore autodidatta!! proverò comunque a dare un occhiata al codice, per vedere se mi ambiento e ci capisco qualcosa. grazie
